import type {
  CropProfile,
  FarmerLocation,
  RecommendationInput,
  SoilDatasetClass,
  SoilTypeInfo,
} from "@/lib/types";

export const farmerLocations: FarmerLocation[] = [
  { name: "Andhra Pradesh", state: "Andhra Pradesh", latitude: 16.5062, longitude: 80.648, zone: "coastal" },
  { name: "Arunachal Pradesh", state: "Arunachal Pradesh", latitude: 27.0844, longitude: 93.6053, zone: "western" },
  { name: "Assam", state: "Assam", latitude: 26.1445, longitude: 91.7362, zone: "delta" },
  { name: "Bihar", state: "Bihar", latitude: 25.5941, longitude: 85.1376, zone: "delta" },
  { name: "Chhattisgarh", state: "Chhattisgarh", latitude: 21.2514, longitude: 81.6296, zone: "dryland" },
  { name: "Goa", state: "Goa", latitude: 15.4909, longitude: 73.8278, zone: "coastal" },
  { name: "Gujarat", state: "Gujarat", latitude: 23.2156, longitude: 72.6369, zone: "dryland" },
  { name: "Haryana", state: "Haryana", latitude: 30.7333, longitude: 76.7794, zone: "dryland" },
  { name: "Himachal Pradesh", state: "Himachal Pradesh", latitude: 31.1048, longitude: 77.1734, zone: "western" },
  { name: "Jharkhand", state: "Jharkhand", latitude: 23.3441, longitude: 85.3096, zone: "dryland" },
  { name: "Karnataka", state: "Karnataka", latitude: 12.9716, longitude: 77.5946, zone: "western" },
  { name: "Kerala", state: "Kerala", latitude: 8.5241, longitude: 76.9366, zone: "coastal" },
  { name: "Madhya Pradesh", state: "Madhya Pradesh", latitude: 23.2599, longitude: 77.4126, zone: "dryland" },
  { name: "Maharashtra", state: "Maharashtra", latitude: 18.5204, longitude: 73.8567, zone: "dryland" },
  { name: "Manipur", state: "Manipur", latitude: 24.817, longitude: 93.9368, zone: "delta" },
  { name: "Meghalaya", state: "Meghalaya", latitude: 25.5788, longitude: 91.8933, zone: "western" },
  { name: "Mizoram", state: "Mizoram", latitude: 23.7307, longitude: 92.7173, zone: "western" },
  { name: "Nagaland", state: "Nagaland", latitude: 25.6751, longitude: 94.1086, zone: "western" },
  { name: "Odisha", state: "Odisha", latitude: 20.2961, longitude: 85.8245, zone: "coastal" },
  { name: "Punjab", state: "Punjab", latitude: 30.7333, longitude: 76.7794, zone: "delta" },
  { name: "Rajasthan", state: "Rajasthan", latitude: 26.9124, longitude: 75.7873, zone: "dryland" },
  { name: "Sikkim", state: "Sikkim", latitude: 27.3389, longitude: 88.6065, zone: "western" },
  { name: "Tamil Nadu", state: "Tamil Nadu", latitude: 13.0827, longitude: 80.2707, zone: "coastal" },
  { name: "Telangana", state: "Telangana", latitude: 17.385, longitude: 78.4867, zone: "dryland" },
  { name: "Tripura", state: "Tripura", latitude: 23.8315, longitude: 91.2868, zone: "delta" },
  { name: "Uttar Pradesh", state: "Uttar Pradesh", latitude: 26.8467, longitude: 80.9462, zone: "delta" },
  { name: "Uttarakhand", state: "Uttarakhand", latitude: 30.3165, longitude: 78.0322, zone: "western" },
  { name: "West Bengal", state: "West Bengal", latitude: 22.5726, longitude: 88.3639, zone: "delta" },
  { name: "Andaman and Nicobar Islands", state: "Andaman and Nicobar Islands", latitude: 11.6234, longitude: 92.7265, zone: "coastal" },
  { name: "Chandigarh", state: "Chandigarh", latitude: 30.7333, longitude: 76.7794, zone: "dryland" },
  { name: "Dadra and Nagar Haveli and Daman and Diu", state: "Dadra and Nagar Haveli and Daman and Diu", latitude: 20.3974, longitude: 72.8328, zone: "coastal" },
  { name: "Delhi", state: "Delhi", latitude: 28.6139, longitude: 77.209, zone: "dryland" },
  { name: "Jammu and Kashmir", state: "Jammu and Kashmir", latitude: 34.0837, longitude: 74.7973, zone: "western" },
  { name: "Ladakh", state: "Ladakh", latitude: 34.1526, longitude: 77.5771, zone: "western" },
  { name: "Lakshadweep", state: "Lakshadweep", latitude: 10.5667, longitude: 72.6417, zone: "coastal" },
  { name: "Puducherry", state: "Puducherry", latitude: 11.9416, longitude: 79.8083, zone: "coastal" },
];

export const defaultRecommendationInput: RecommendationInput = {
  soilType: "Loamy",
  season: "Kharif",
  temperature: 30,
  rainfall: 900,
  humidity: 78,
  waterAvailability: "High",
  location: "Tamil Nadu",
};

export const soilDatasetFamilies: Record<SoilDatasetClass, string> = {
  Alluvial_Soil: "Alluvial Soil",
  Arid_Soil: "Arid Soil",
  Black_Soil: "Black Soil",
  Laterite_Soil: "Laterite Soil",
  Mountain_Soil: "Mountain Soil",
  Red_Soil: "Red Soil",
  Yellow_Soil: "Yellow Soil",
};

export const soilDatasetToRecommendationSoil: Record<SoilDatasetClass, RecommendationInput["soilType"]> = {
  Alluvial_Soil: "Loamy",
  Arid_Soil: "Sandy",
  Black_Soil: "Clay",
  Laterite_Soil: "Loamy",
  Mountain_Soil: "Loamy",
  Red_Soil: "Loamy",
  Yellow_Soil: "Sandy",
};

export const soilTypeDetails: SoilTypeInfo[] = [
  {
    value: "Loamy",
    label: "Loamy",
    description: "Balanced soil that holds moisture but still drains well.",
    fieldExample: "Feels soft and crumbly, like a mix of garden soil, sand, and clay.",
  },
  {
    value: "Alluvial",
    label: "Alluvial",
    description: "Fertile river-belt soil with good nutrient carryover.",
    fieldExample: "Common near river plains where silt settles after water flow.",
  },
  {
    value: "Black",
    label: "Black",
    description: "Heavy dark soil that stores moisture for longer periods.",
    fieldExample: "Sticky when wet, cracks when dry, and often supports cotton well.",
  },
  {
    value: "Red",
    label: "Red",
    description: "Light to medium soil with lower organic matter and faster drainage.",
    fieldExample: "Rust-colored soil that warms quickly and needs regular feeding.",
  },
  {
    value: "Clay",
    label: "Clay",
    description: "Dense soil with strong water-holding capacity.",
    fieldExample: "Feels smooth and sticky, forms a ribbon when pressed between fingers.",
  },
  {
    value: "Sandy",
    label: "Sandy",
    description: "Fast-draining soil that dries quickly after irrigation or rain.",
    fieldExample: "Feels gritty in the hand and does not stick together easily.",
  },
];

export const cropProfiles: CropProfile[] = [
  {
    id: "rice",
    name: "Rice",
    summary: "Reliable cereal for humid, water-supported fields with strong staple demand.",
    soilTypes: ["Alluvial", "Clay", "Loamy"],
    seasons: ["Kharif", "Summer"],
    zones: ["coastal", "delta"],
    waterNeed: "High",
    growingWindow: "110-135 days",
    marketOutlook: "Stable",
    caution: "Rice loses performance quickly when standing moisture breaks during tillering.",
    baseYieldPerAcreKg: 2200,
    estimatedCostPerAcre: 36000,
    marketAliases: ["rice", "paddy", "dhan"],
  },
  {
    id: "maize",
    name: "Maize",
    summary: "Flexible grain crop that responds well under moderate rainfall and balanced fertility.",
    soilTypes: ["Loamy", "Black", "Alluvial"],
    seasons: ["Kharif", "Rabi"],
    zones: ["western", "dryland", "delta"],
    waterNeed: "Medium",
    growingWindow: "95-110 days",
    marketOutlook: "Stable",
    caution: "Drainage matters because wet roots can reduce cob filling and stand strength.",
    baseYieldPerAcreKg: 2400,
    estimatedCostPerAcre: 26000,
    marketAliases: ["maize", "corn"],
  },
  {
    id: "chickpea",
    name: "Chickpea",
    summary: "A cool-season pulse that suits moderate moisture and lighter irrigation schedules.",
    soilTypes: ["Loamy", "Black", "Red"],
    seasons: ["Rabi"],
    zones: ["dryland", "western"],
    waterNeed: "Low",
    growingWindow: "95-115 days",
    marketOutlook: "Stable",
    caution: "Too much late-season moisture can increase disease pressure during pod setting.",
    baseYieldPerAcreKg: 900,
    estimatedCostPerAcre: 16000,
    marketAliases: ["chickpea", "gram", "chana", "bengal gram"],
  },
  {
    id: "kidneybeans",
    name: "Kidney Beans",
    summary: "Pulse option for cooler windows where uniform moisture and drainage can be managed.",
    soilTypes: ["Loamy", "Alluvial", "Red"],
    seasons: ["Rabi"],
    zones: ["western"],
    waterNeed: "Medium",
    growingWindow: "100-120 days",
    marketOutlook: "Emerging",
    caution: "Avoid hard waterlogging because the crop is sensitive during establishment.",
    baseYieldPerAcreKg: 850,
    estimatedCostPerAcre: 19000,
    marketAliases: ["kidney beans", "kidneybeans", "rajma"],
  },
  {
    id: "pigeonpeas",
    name: "Pigeon Peas",
    summary: "Longer-duration pulse for dry belts that benefit from steady but not excessive rain.",
    soilTypes: ["Loamy", "Red", "Black"],
    seasons: ["Kharif"],
    zones: ["dryland", "western"],
    waterNeed: "Low",
    growingWindow: "140-180 days",
    marketOutlook: "Stable",
    caution: "The long crop cycle means late sowing can trim flowering and final pod load.",
    baseYieldPerAcreKg: 800,
    estimatedCostPerAcre: 17000,
    marketAliases: ["pigeon peas", "pigeonpeas", "arhar", "tur", "red gram"],
  },
  {
    id: "mothbeans",
    name: "Moth Beans",
    summary: "Hardy pulse for low-rainfall pockets where resilience matters more than peak yield.",
    soilTypes: ["Sandy", "Red", "Loamy"],
    seasons: ["Kharif", "Summer"],
    zones: ["dryland"],
    waterNeed: "Low",
    growingWindow: "70-90 days",
    marketOutlook: "Emerging",
    caution: "Yield stability improves when early weeds are controlled aggressively.",
    baseYieldPerAcreKg: 500,
    estimatedCostPerAcre: 12000,
    marketAliases: ["moth beans", "mothbeans", "mat bean"],
  },
  {
    id: "mungbean",
    name: "Mung Bean",
    summary: "Short-duration pulse that fits quick rotations and moderate summer heat.",
    soilTypes: ["Loamy", "Sandy", "Red"],
    seasons: ["Rabi", "Summer"],
    zones: ["dryland", "delta", "coastal"],
    waterNeed: "Low",
    growingWindow: "65-80 days",
    marketOutlook: "Strong",
    caution: "Harvest timing matters because pods mature quickly and can shatter if delayed.",
    baseYieldPerAcreKg: 650,
    estimatedCostPerAcre: 13000,
    marketAliases: ["mung bean", "mungbean", "moong", "green gram"],
  },
  {
    id: "blackgram",
    name: "Black Gram",
    summary: "Popular pulse for lower water conditions with reliable local dal demand.",
    soilTypes: ["Loamy", "Clay", "Red"],
    seasons: ["Kharif", "Rabi"],
    zones: ["delta", "dryland", "coastal"],
    waterNeed: "Low",
    growingWindow: "80-95 days",
    marketOutlook: "Strong",
    caution: "Extended humidity during flowering raises the risk of foliar disease flare-ups.",
    baseYieldPerAcreKg: 700,
    estimatedCostPerAcre: 14500,
    marketAliases: ["black gram", "blackgram", "urd", "urad"],
  },
  {
    id: "lentil",
    name: "Lentil",
    summary: "Cool-season pulse for moderate climates and lighter water availability.",
    soilTypes: ["Loamy", "Alluvial", "Red"],
    seasons: ["Rabi"],
    zones: ["western", "dryland"],
    waterNeed: "Low",
    growingWindow: "100-115 days",
    marketOutlook: "Stable",
    caution: "Too much late rainfall can reduce grain quality and harvest ease.",
    baseYieldPerAcreKg: 700,
    estimatedCostPerAcre: 15000,
    marketAliases: ["lentil", "masur"],
  },
  {
    id: "pomegranate",
    name: "Pomegranate",
    summary: "High-value fruit option for dry belts with controlled irrigation and careful orchard care.",
    soilTypes: ["Loamy", "Black", "Red"],
    seasons: ["Kharif", "Summer"],
    zones: ["dryland", "western"],
    waterNeed: "Medium",
    growingWindow: "6-7 months to harvest",
    marketOutlook: "Strong",
    caution: "Fruit cracking becomes more common when irrigation swings sharply.",
    baseYieldPerAcreKg: 5000,
    estimatedCostPerAcre: 85000,
    marketAliases: ["pomegranate", "anar"],
  },
  {
    id: "banana",
    name: "Banana",
    summary: "Water-responsive fruit crop that performs best where fertility and irrigation are dependable.",
    soilTypes: ["Alluvial", "Loamy", "Clay"],
    seasons: ["Kharif", "Summer"],
    zones: ["coastal", "delta", "western"],
    waterNeed: "High",
    growingWindow: "10-12 months",
    marketOutlook: "Strong",
    caution: "Banana demands steady feeding, so weak nutrition quickly shows in bunch size.",
    baseYieldPerAcreKg: 12000,
    estimatedCostPerAcre: 125000,
    marketAliases: ["banana"],
  },
  {
    id: "mango",
    name: "Mango",
    summary: "Fruit crop for warm districts with a strong marketing upside during harvest windows.",
    soilTypes: ["Alluvial", "Loamy", "Red"],
    seasons: ["Summer", "Kharif"],
    zones: ["coastal", "dryland", "western"],
    waterNeed: "Medium",
    growingWindow: "5-6 months to harvest",
    marketOutlook: "Strong",
    caution: "Flowering and fruit set become less reliable when humidity stays too high.",
    baseYieldPerAcreKg: 3500,
    estimatedCostPerAcre: 52000,
    marketAliases: ["mango"],
  },
  {
    id: "grapes",
    name: "Grapes",
    summary: "Premium fruit option where drainage, pruning, and close crop care can be managed.",
    soilTypes: ["Loamy", "Black", "Alluvial"],
    seasons: ["Rabi", "Summer"],
    zones: ["western", "dryland"],
    waterNeed: "Medium",
    growingWindow: "5-6 months to harvest",
    marketOutlook: "Strong",
    caution: "Canopy and disease management are critical through humid spells.",
    baseYieldPerAcreKg: 7000,
    estimatedCostPerAcre: 98000,
    marketAliases: ["grapes", "grape"],
  },
  {
    id: "watermelon",
    name: "Watermelon",
    summary: "Short fruit crop suited to warm windows with moderate irrigation control.",
    soilTypes: ["Sandy", "Loamy", "Alluvial"],
    seasons: ["Summer"],
    zones: ["dryland", "western", "coastal"],
    waterNeed: "Medium",
    growingWindow: "80-100 days",
    marketOutlook: "Emerging",
    caution: "Fruit quality drops when vines face sudden water stress during sizing.",
    baseYieldPerAcreKg: 8000,
    estimatedCostPerAcre: 45000,
    marketAliases: ["watermelon", "water melon", "tarbooj"],
  },
  {
    id: "muskmelon",
    name: "Muskmelon",
    summary: "Heat-loving fruit crop that works best on lighter soils with good drainage.",
    soilTypes: ["Sandy", "Loamy", "Alluvial"],
    seasons: ["Summer"],
    zones: ["dryland", "western", "coastal"],
    waterNeed: "Medium",
    growingWindow: "75-90 days",
    marketOutlook: "Emerging",
    caution: "Over-irrigation can reduce sweetness and increase fruit-skin issues.",
    baseYieldPerAcreKg: 6500,
    estimatedCostPerAcre: 42000,
    marketAliases: ["muskmelon", "musk melon", "kharbuja", "melon"],
  },
  {
    id: "apple",
    name: "Apple",
    summary: "Cooler-climate fruit crop that is only practical where temperature stress stays low.",
    soilTypes: ["Loamy", "Alluvial"],
    seasons: ["Rabi", "Summer"],
    zones: ["western"],
    waterNeed: "Medium",
    growingWindow: "4-5 months to harvest",
    marketOutlook: "Strong",
    caution: "Warm plains conditions can sharply reduce flowering quality and fruit finish.",
    baseYieldPerAcreKg: 4500,
    estimatedCostPerAcre: 78000,
    marketAliases: ["apple"],
  },
  {
    id: "orange",
    name: "Orange",
    summary: "Citrus crop for moderate climates with careful nutrient and irrigation management.",
    soilTypes: ["Loamy", "Red", "Alluvial"],
    seasons: ["Rabi", "Summer"],
    zones: ["western", "dryland"],
    waterNeed: "Medium",
    growingWindow: "6-8 months to harvest",
    marketOutlook: "Strong",
    caution: "Irregular watering can reduce fruit size and uniformity at harvest.",
    baseYieldPerAcreKg: 4200,
    estimatedCostPerAcre: 68000,
    marketAliases: ["orange"],
  },
  {
    id: "papaya",
    name: "Papaya",
    summary: "Fast fruiting crop for warm, moist conditions where drainage is still maintained.",
    soilTypes: ["Loamy", "Alluvial", "Red"],
    seasons: ["Kharif", "Summer"],
    zones: ["coastal", "delta", "western"],
    waterNeed: "Medium",
    growingWindow: "8-10 months",
    marketOutlook: "Strong",
    caution: "Papaya roots dislike standing water, even though the crop likes warm humidity.",
    baseYieldPerAcreKg: 9000,
    estimatedCostPerAcre: 76000,
    marketAliases: ["papaya"],
  },
  {
    id: "coconut",
    name: "Coconut",
    summary: "Long-horizon plantation crop suited to coastal belts and dependable irrigation support.",
    soilTypes: ["Alluvial", "Loamy", "Sandy"],
    seasons: ["Kharif", "Summer"],
    zones: ["coastal", "delta", "western"],
    waterNeed: "High",
    growingWindow: "12 months for full nut cycle",
    marketOutlook: "Stable",
    caution: "Yields are steadier when palms never face prolonged moisture stress.",
    baseYieldPerAcreKg: 3500,
    estimatedCostPerAcre: 54000,
    marketAliases: ["coconut", "copra"],
  },
  {
    id: "cotton",
    name: "Cotton",
    summary: "Warm-season fiber crop for black and loamy soils with a longer growing window.",
    soilTypes: ["Black", "Loamy", "Red"],
    seasons: ["Kharif"],
    zones: ["western", "dryland"],
    waterNeed: "Medium",
    growingWindow: "150-180 days",
    marketOutlook: "Stable",
    caution: "Late sowing compresses boll development and can reduce lint quality.",
    baseYieldPerAcreKg: 1100,
    estimatedCostPerAcre: 30000,
    marketAliases: ["cotton", "kapas"],
  },
  {
    id: "jute",
    name: "Jute",
    summary: "Fiber crop for humid belts with stronger rainfall and warm establishment conditions.",
    soilTypes: ["Alluvial", "Loamy", "Clay"],
    seasons: ["Kharif"],
    zones: ["coastal", "delta"],
    waterNeed: "High",
    growingWindow: "120-150 days",
    marketOutlook: "Emerging",
    caution: "The crop performs best when early moisture is strong and uninterrupted.",
    baseYieldPerAcreKg: 1400,
    estimatedCostPerAcre: 25000,
    marketAliases: ["jute"],
  },
  {
    id: "coffee",
    name: "Coffee",
    summary: "Specialty plantation crop for moderated temperatures, humidity, and attentive orchard care.",
    soilTypes: ["Loamy", "Red"],
    seasons: ["Kharif", "Rabi"],
    zones: ["western"],
    waterNeed: "Medium",
    growingWindow: "7-9 months to picking",
    marketOutlook: "Strong",
    caution: "Shade, pruning, and berry disease control are all central to a stable harvest.",
    baseYieldPerAcreKg: 700,
    estimatedCostPerAcre: 42000,
    marketAliases: ["coffee"],
  },
];
